add_newline = false

[battery]
full_symbol = "ğŸ”ŒğŸ‘"
charging_symbol = "ğŸ”Œâš¡ï¸"
discharging_symbol = "ğŸ”‹"
unknown_symbol = "ğŸ”ŒğŸ"
empty_symbol = "ğŸ”‹ğŸ’€"
format = "[$symbol$percentage ]($style)"

[[battery.display]]
threshold = 10
style = "bold white bg:red"
[[battery.display]]
threshold = 20
style = "bold red"
[[battery.display]]
threshold = 30
style = "red"
[[battery.display]]
threshold = 50
style = "yellow"
[[battery.display]]
threshold = 100
style = "green"

[nodejs]
symbol = "node "

[time]
disabled = false
style = "green"

[git_metrics]
disabled = false
